;; Generated by x64-scaled-index.py; do not edit.
(module
  (memory 1)
  (func (export "fill") (param $seed i32)
    (local $j i32)
    (loop $l
      (i32.store (i32.shl (local.get $j) (i32.const 2))
        (i32.xor (i32.mul (local.get $j) (i32.const 0x01000193))
                 (local.get $seed)))
      (local.set $j (i32.add (local.get $j) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $j) (i32.const 16384)))))

  (func (export "hash") (param $p i32) (param $cnt i32) (result i32)
    (local $acc i32)
    (local.set $acc (i32.const 0x811c9dc5))
    (loop $l
      (local.set $acc (i32.mul (i32.xor (local.get $acc)
        (i32.load (local.get $p))) (i32.const 0x01000193)))
      (local.set $p (i32.add (local.get $p) (i32.const 4)))
      (local.set $cnt (i32.sub (local.get $cnt) (i32.const 1)))
      (br_if $l (local.get $cnt)))
    (local.get $acc))

  (func (export "st1_7fffffff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 2147483647))
        (i32.const 1)))
      (i32.store16 (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st1_80000000") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const -2147483648))
        (i32.const 1)))
      (i32.store16 (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st1_ffffffff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const -1))
        (i32.const 1)))
      (i32.store16 (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st1_80000fff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const -2147479553))
        (i32.const 1)))
      (i32.store16 (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st2_3fffffff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 1073741823))
        (i32.const 2)))
      (i32.store (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st2_40000000") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 1073741824))
        (i32.const 2)))
      (i32.store (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st2_40000fff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 1073745919))
        (i32.const 2)))
      (i32.store (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st2_3fff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 16383))
        (i32.const 2)))
      (i32.store (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st3_1fffffff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i64)
    (local.set $v (i64.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 536870911))
        (i32.const 3)))
      (i64.store (local.get $a) (local.get $v))
      (local.set $v (i64.add (local.get $v) (i64.const 0x9E3779B97F4A7C15)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st3_20000000") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i64)
    (local.set $v (i64.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 536870912))
        (i32.const 3)))
      (i64.store (local.get $a) (local.get $v))
      (local.set $v (i64.add (local.get $v) (i64.const 0x9E3779B97F4A7C15)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st3_1fff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i64)
    (local.set $v (i64.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 8191))
        (i32.const 3)))
      (i64.store (local.get $a) (local.get $v))
      (local.set $v (i64.add (local.get $v) (i64.const 0x9E3779B97F4A7C15)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st2_b_3fff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 16383))
        (i32.const 2)))
      (i32.store8 (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st3_w_1fff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 8191))
        (i32.const 3)))
      (i32.store (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "st1_b_7fff") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 32767))
        (i32.const 1)))
      (i32.store8 (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "ld2_3fff") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 16383))
        (i32.const 2)))
      (local.set $acc (i32.add (local.get $acc) (i32.load (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld2_3fffffff") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 1073741823))
        (i32.const 2)))
      (local.set $acc (i32.add (local.get $acc) (i32.load (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld2_40000000") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 1073741824))
        (i32.const 2)))
      (local.set $acc (i32.add (local.get $acc) (i32.load (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld1_s16_7fff") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 32767))
        (i32.const 1)))
      (local.set $acc (i32.add (local.get $acc) (i32.load16_s (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld1_u16_7fffffff") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 2147483647))
        (i32.const 1)))
      (local.set $acc (i32.add (local.get $acc) (i32.load16_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld1_u16_ffffffff") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const -1))
        (i32.const 1)))
      (local.set $acc (i32.add (local.get $acc) (i32.load16_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld2_s8_3fff") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 16383))
        (i32.const 2)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_s (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld3_u8_1fff") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 8191))
        (i32.const 3)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld3_64_1fff") (param $n i32) (param $x i32) (result i64)
    (local $i i32) (local $a i32) (local $acc i64)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 8191))
        (i32.const 3)))
      (local.set $acc (i64.add (local.get $acc) (i64.load (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld3_64_1fffffff") (param $n i32) (param $x i32) (result i64)
    (local $i i32) (local $a i32) (local $acc i64)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 536870911))
        (i32.const 3)))
      (local.set $acc (i64.add (local.get $acc) (i64.load (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ld3_64_20000001") (param $n i32) (param $x i32) (result i64)
    (local $i i32) (local $a i32) (local $acc i64)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 536870913))
        (i32.const 3)))
      (local.set $acc (i64.add (local.get $acc) (i64.load (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc0") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 0)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc1") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 1)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc3") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 3)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc4") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 4)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc32") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 32)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc33") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 33)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc34") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 34)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc35") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 35)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc36") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 36)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc66") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 66)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "ldc99") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 4095))
        (i32.const 99)))
      (local.set $acc (i32.add (local.get $acc) (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "stc34") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 16383))
        (i32.const 34)))
      (i32.store (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "stc36") (param $n i32) (param $x i32)
    (local $i i32) (local $a i32) (local $v i32)
    (local.set $v (i32.const 0x12345))
    (loop $l
      (local.set $a (i32.shl
        (i32.and (i32.add (local.get $i) (local.get $x)) (i32.const 16383))
        (i32.const 36)))
      (i32.store (local.get $a) (local.get $v))
      (local.set $v (i32.add (local.get $v) (i32.const 0x9E3779B1)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n)))))

  (func (export "after") (param $n i32) (result i32)
    (local $i i32) (local $a i32)
    (loop $l
      (local.set $a (i32.shl (i32.and (local.get $i) (i32.const 0x3fff))
                             (i32.const 2)))
      (i32.store (local.get $a) (local.get $i))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (i32.add (local.get $a) (i32.load (local.get $a))))

  (func (export "carried") (param $n i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (local.set $a (i32.const 1000))
    (loop $l
      (if (i32.and (local.get $i) (i32.const 1))
        (then (local.set $acc (i32.add (local.get $acc) (local.get $a)))))
      (local.set $a (i32.shl (i32.and (local.get $i) (i32.const 0x3fff))
                             (i32.const 2)))
      (i32.store (local.get $a) (i32.xor (local.get $i) (local.get $acc)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "sameline") (param $n i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl (i32.and (local.get $i) (i32.const 0x1fff))
                             (i32.const 3)))
      (i32.store (local.get $a) (local.get $acc))
      (local.set $acc (i32.add (local.get $acc) (local.get $a)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "onearm") (param $n i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl (i32.and (local.get $i) (i32.const 0x7fff))
                             (i32.const 1)))
      (i32.store16 (local.get $a) (local.get $i))
      (if (i32.eqz (i32.and (local.get $i) (i32.const 3)))
        (then (local.set $acc (i32.xor (local.get $acc) (local.get $a))))
        (else (local.set $acc (i32.add (local.get $acc) (i32.const 1)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "redef") (param $n i32) (result i32)
    (local $i i32) (local $a i32)
    (loop $l
      (local.set $a (i32.shl (i32.and (local.get $i) (i32.const 0x3fff))
                             (i32.const 2)))
      (i32.store (local.get $a) (local.get $i))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.set $a (i32.const 12))
    (i32.add (local.get $a) (i32.load (local.get $a))))

  (func (export "twice") (param $n i32) (result i32)
    (local $i i32) (local $a i32) (local $acc i32)
    (loop $l
      (local.set $a (i32.shl (i32.and (local.get $i) (i32.const 0x3fff))
                             (i32.const 2)))
      (i32.store (local.get $a) (i32.mul (local.get $i) (i32.const 0x01010101)))
      (local.set $acc (i32.add (local.get $acc)
        (i32.load8_u (local.get $a))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "fwd") (param $n i32) (result i32)
    (local $i i32) (local $acc i32) (local $address i32)
    (loop $l
      (local.set $address (i32.shl (i32.and (local.get $i) (i32.const 16383))
                                   (i32.const 2)))
      (i32.store (local.get $address) (local.get $i))
      (local.set $acc (i32.add (local.get $acc)
        (i32.load (local.get $address))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "selfval") (param $n i32) (result i32)
    (local $i i32) (local $a i32)
    (loop $l
      (local.set $a (i32.shl (i32.and (local.get $i) (i32.const 0x3fff))
                             (i32.const 2)))
      (i32.store (local.get $a) (local.get $a))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (i32.const 0))

  (func (export "chain") (param $n i32) (result i32)
    (local $i i32) (local $m i32) (local $acc i32)
    (loop $l
      (local.set $m (i32.and (i32.load8_s (local.get $i)) (i32.const 0xff)))
      (i32.store (i32.shl (local.get $m) (i32.const 2)) (local.get $m))
      (local.set $acc (i32.add (local.get $acc) (i32.load
        (i32.shl (i32.and (i32.add (local.get $i) (local.get $acc))
                          (i32.const 0x3fff)) (i32.const 2)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (local.get $acc))

  (func (export "between") (param $n i32) (param $x i32) (result i32)
    (local $i i32) (local $a i32)
    (loop $l
      (local.set $a (i32.shl (i32.and (i32.add (local.get $i) (local.get $x))
                                      (i32.const 0x1fff)) (i32.const 3)))
      (i64.store (local.get $a)
        (i64.add (i64.mul (i64.xor (i64.const 0x1234567890)
                                   (i64.const 0x55))
                          (i64.const 0x45))
                 (i64.const 7)))
      (i32.store (local.get $a)
        (i32.add (i32.mul (i32.xor (local.get $i) (local.get $x))
                          (i32.const 0x45))
                 (i32.mul (i32.add (local.get $i) (i32.const 7))
                          (i32.sub (local.get $x) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (i32.const 1))

  (func (export "between1") (param $n i32) (param $x i32) (result i32)
    (local $i i32)
    (loop $l
      (i32.store (i32.shl (i32.and (i32.add (local.get $i) (local.get $x))
                                   (i32.const 0x3fff)) (i32.const 2))
        (i32.add (i32.mul (i32.xor (local.get $i) (local.get $x))
                          (i32.const 0x45))
                 (i32.mul (i32.add (local.get $i) (i32.const 7))
                          (i32.sub (local.get $x) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $l (i32.lt_u (local.get $i) (local.get $n))))
    (i32.const 1))

  (func (export "wrapconst") (result i32)
    (i32.store (i32.shl (i32.const 0x40000001) (i32.const 2))
               (i32.const 0x11223344))
    (i32.load (i32.const 4)))

)

(assert_return (invoke "fill" (i32.const 1515870810)))
(assert_trap (invoke "st2_3fffffff" (i32.const 40) (i32.const 16368)) "out of bounds memory access")
(assert_return (invoke "hash" (i32.const 65472) (i32.const 16)) (i32.const 3085205))
(assert_return (invoke "st2_3fff" (i32.const 100) (i32.const 16336)))
(assert_return (invoke "hash" (i32.const 65344) (i32.const 48)) (i32.const 848380597))
(assert_return (invoke "hash" (i32.const 0) (i32.const 20)) (i32.const -905994283))
(assert_trap (invoke "st1_7fffffff" (i32.const 30) (i32.const 32752)) "out of bounds memory access")
(assert_return (invoke "hash" (i32.const 65504) (i32.const 8)) (i32.const 659977029))
(assert_trap (invoke "st3_1fffffff" (i32.const 12) (i32.const 8186)) "out of bounds memory access")
(assert_return (invoke "hash" (i32.const 65488) (i32.const 12)) (i32.const 639355541))
(assert_return (invoke "st3_1fff" (i32.const 20) (i32.const 8184)))
(assert_return (invoke "hash" (i32.const 65472) (i32.const 16)) (i32.const 1984579472))
(assert_return (invoke "hash" (i32.const 0) (i32.const 24)) (i32.const -249213455))
(assert_return (invoke "st2_b_3fff" (i32.const 64) (i32.const 16352)))
(assert_return (invoke "hash" (i32.const 65408) (i32.const 32)) (i32.const -1488459035))
(assert_return (invoke "st3_w_1fff" (i32.const 16) (i32.const 8180)))
(assert_return (invoke "hash" (i32.const 65440) (i32.const 24)) (i32.const 58165765))
(assert_return (invoke "st1_b_7fff" (i32.const 50) (i32.const 32744)))
(assert_return (invoke "hash" (i32.const 65488) (i32.const 12)) (i32.const -31747267))
(assert_return (invoke "hash" (i32.const 0) (i32.const 8)) (i32.const 1197888837))
(assert_trap (invoke "st2_3fffffff" (i32.const 4) (i32.const 1073741808)) "out of bounds memory access")
(assert_trap (invoke "st1_7fffffff" (i32.const 3) (i32.const 2147483632)) "out of bounds memory access")
(assert_trap (invoke "st3_1fffffff" (i32.const 2) (i32.const 536870896)) "out of bounds memory access")
(assert_trap (invoke "st2_3fffffff" (i32.const 3) (i32.const 65536)) "out of bounds memory access")
(assert_return (invoke "hash" (i32.const 0) (i32.const 16)) (i32.const 492101385))
(assert_return (invoke "st2_40000000" (i32.const 8) (i32.const 1073741824)))
(assert_return (invoke "hash" (i32.const 0) (i32.const 4)) (i32.const 1079732508))
(assert_return (invoke "st2_40000fff" (i32.const 20) (i32.const 1073745904)))
(assert_return (invoke "hash" (i32.const 16320) (i32.const 16)) (i32.const 3085205))
(assert_return (invoke "hash" (i32.const 0) (i32.const 8)) (i32.const -1580061635))
(assert_return (invoke "st1_80000000" (i32.const 5) (i32.const -2147483648)))
(assert_return (invoke "hash" (i32.const 0) (i32.const 2)) (i32.const -1230864506))
(assert_return (invoke "st1_ffffffff" (i32.const 12) (i32.const -2147483646)))
(assert_return (invoke "hash" (i32.const 0) (i32.const 8)) (i32.const 1355031085))
(assert_return (invoke "st1_80000fff" (i32.const 9) (i32.const -2147479560)))
(assert_return (invoke "hash" (i32.const 8160) (i32.const 16)) (i32.const 768649353))
(assert_return (invoke "hash" (i32.const 0) (i32.const 4)) (i32.const 767819627))
(assert_return (invoke "st3_20000000" (i32.const 3) (i32.const 536870912)))
(assert_return (invoke "hash" (i32.const 0) (i32.const 2)) (i32.const -352027260))
(assert_return (invoke "st2_3fff" (i32.const 40) (i32.const 16376)))
(assert_return (invoke "hash" (i32.const 65504) (i32.const 8)) (i32.const 1752945133))
(assert_return (invoke "hash" (i32.const 0) (i32.const 8)) (i32.const 1445072477))
(assert_return (invoke "st3_1fff" (i32.const 10) (i32.const 8188)))
(assert_return (invoke "hash" (i32.const 65504) (i32.const 8)) (i32.const -1483970988))
(assert_trap (invoke "st1_7fffffff" (i32.const 10) (i32.const 32764)) "out of bounds memory access")
(assert_return (invoke "hash" (i32.const 65520) (i32.const 4)) (i32.const 2039276444))
(assert_return (invoke "st2_b_3fff" (i32.const 10) (i32.const 16380)))
(assert_return (invoke "hash" (i32.const 65520) (i32.const 4)) (i32.const -1836127003))
(assert_return (invoke "fill" (i32.const 324508639)))
(assert_return (invoke "ld2_3fff" (i32.const 1000) (i32.const 7)) (i32.const 1334765132))
(assert_return (invoke "ld2_3fff" (i32.const 40000) (i32.const 12288)) (i32.const 2050646048))
(assert_trap (invoke "ld2_3fffffff" (i32.const 300) (i32.const 16128)) "out of bounds memory access")
(assert_trap (invoke "ld2_3fffffff" (i32.const 300) (i32.const 261888)) "out of bounds memory access")
(assert_trap (invoke "ld2_3fffffff" (i32.const 2) (i32.const 1073741823)) "out of bounds memory access")
(assert_return (invoke "ld2_40000000" (i32.const 50) (i32.const 1073741824)) (i32.const -954437234))
(assert_return (invoke "ld1_s16_7fff" (i32.const 70000) (i32.const 4660)) (i32.const -2937574))
(assert_trap (invoke "ld1_u16_7fffffff" (i32.const 500) (i32.const 32512)) "out of bounds memory access")
(assert_trap (invoke "ld1_u16_7fffffff" (i32.const 500) (i32.const 524032)) "out of bounds memory access")
(assert_trap (invoke "ld1_u16_ffffffff" (i32.const 20) (i32.const 2147483640)) "out of bounds memory access")
(assert_return (invoke "ld1_u16_ffffffff" (i32.const 20) (i32.const -2147483648)) (i32.const 445765))
(assert_return (invoke "ld2_s8_3fff" (i32.const 20000) (i32.const 3)) (i32.const -10000))
(assert_return (invoke "ld3_u8_1fff" (i32.const 9000) (i32.const 7936)) (i32.const 1152272))
(assert_return (invoke "ld3_64_1fff" (i32.const 9000) (i32.const 256)) (i64.const 4692627015342515728))
(assert_trap (invoke "ld3_64_1fffffff" (i32.const 100) (i32.const 8128)) "out of bounds memory access")
(assert_trap (invoke "ld3_64_1fffffff" (i32.const 100) (i32.const 8176)) "out of bounds memory access")
(assert_return (invoke "ld3_64_20000001" (i32.const 40) (i32.const 536870912)) (i64.const -5354637111201881888))
(assert_return (invoke "ld3_64_20000001" (i32.const 40) (i32.const 1073741792)) (i64.const -5354637111201881888))
(assert_return (invoke "fill" (i32.const 610839776)))
(assert_return (invoke "ldc0" (i32.const 5000) (i32.const 11)) (i32.const 614681))
(assert_return (invoke "ldc1" (i32.const 5000) (i32.const 11)) (i32.const 579105))
(assert_return (invoke "ldc3" (i32.const 5000) (i32.const 11)) (i32.const 634872))
(assert_return (invoke "ldc4" (i32.const 5000) (i32.const 11)) (i32.const 630128))
(assert_return (invoke "ldc32" (i32.const 5000) (i32.const 11)) (i32.const 614681))
(assert_return (invoke "ldc33" (i32.const 5000) (i32.const 11)) (i32.const 579105))
(assert_return (invoke "ldc34" (i32.const 5000) (i32.const 11)) (i32.const 637340))
(assert_return (invoke "ldc35" (i32.const 5000) (i32.const 11)) (i32.const 634872))
(assert_return (invoke "ldc36" (i32.const 5000) (i32.const 11)) (i32.const 630128))
(assert_return (invoke "ldc66" (i32.const 5000) (i32.const 11)) (i32.const 637340))
(assert_return (invoke "ldc99" (i32.const 5000) (i32.const 11)) (i32.const 634872))
(assert_return (invoke "stc34" (i32.const 20) (i32.const 16368)))
(assert_return (invoke "hash" (i32.const 65472) (i32.const 16)) (i32.const 3085205))
(assert_trap (invoke "stc36" (i32.const 5000) (i32.const 0)) "out of bounds memory access")
(assert_return (invoke "fill" (i32.const 195948557)))
(assert_return (invoke "after" (i32.const 37)) (i32.const 180))
(assert_return (invoke "after" (i32.const 16390)) (i32.const 16409))
(assert_return (invoke "carried" (i32.const 1)) (i32.const 0))
(assert_return (invoke "carried" (i32.const 999)) (i32.const 994008))
(assert_return (invoke "hash" (i32.const 0) (i32.const 64)) (i32.const -280368379))
(assert_return (invoke "sameline" (i32.const 3000)) (i32.const 35988000))
(assert_return (invoke "hash" (i32.const 0) (i32.const 32)) (i32.const -1607376699))
(assert_return (invoke "onearm" (i32.const 5000)) (i32.const 9390))
(assert_return (invoke "hash" (i32.const 0) (i32.const 32)) (i32.const 1594414085))
(assert_return (invoke "redef" (i32.const 2)) (i32.const 458770))
(assert_return (invoke "redef" (i32.const 16389)) (i32.const 16399))
(assert_return (invoke "twice" (i32.const 20000)) (i32.const 2546416))
(assert_return (invoke "fwd" (i32.const 70000)) (i32.const -1845002296))
(assert_return (invoke "hash" (i32.const 0) (i32.const 64)) (i32.const 1318586629))
(assert_return (invoke "selfval" (i32.const 100)) (i32.const 0))
(assert_return (invoke "hash" (i32.const 0) (i32.const 100)) (i32.const 305189861))
(assert_return (invoke "chain" (i32.const 3000)) (i32.const 196310087))
(assert_return (invoke "hash" (i32.const 0) (i32.const 256)) (i32.const -1868277563))
(assert_return (invoke "between" (i32.const 3000) (i32.const 5)) (i32.const 1))
(assert_return (invoke "hash" (i32.const 0) (i32.const 256)) (i32.const -1125243236))
(assert_return (invoke "hash" (i32.const 65280) (i32.const 64)) (i32.const 1023872261))
(assert_return (invoke "between" (i32.const 20) (i32.const 8176)) (i32.const 1))
(assert_return (invoke "hash" (i32.const 65408) (i32.const 32)) (i32.const 1421872293))
(assert_return (invoke "between1" (i32.const 20000) (i32.const 9)) (i32.const 1))
(assert_return (invoke "hash" (i32.const 0) (i32.const 256)) (i32.const -1019872827))
(assert_return (invoke "hash" (i32.const 65024) (i32.const 128)) (i32.const -20068155))
(assert_return (invoke "between1" (i32.const 20) (i32.const 16376)) (i32.const 1))
(assert_return (invoke "hash" (i32.const 65504) (i32.const 8)) (i32.const -806192539))
(assert_return (invoke "wrapconst" ) (i32.const 287454020))
