#!/usr/bin/env instantfpc
program StampVersion;

{ Write source/units/Version.inc with a Pascal `PROGRAM_VERSION = '<value>';`
  constant. Wasm.Core {$I}'s the result; `wasmlight --version` reports it.

  The value is, in priority order:
    1. $WASMLIGHT_VERSION_OVERRIDE if set + non-empty — for release builds
       that stamp the git tag into the binary.
    2. otherwise [package].version from lwpt.toml — the dev / unreleased
       version reported by locally-built binaries.

  The generated file is committed even though it is generated, so a fresh
  clone compiles before any hook has run. The `prebuild` and `pretest`
  hooks in lwpt.toml keep it in step with the manifest; drift is caught by
  the formatter/CI gate, not by a compile failure.

  Deliberately self-contained (naive line scan for the first
  `version = "..."` line inside [package]) so it has no dependency on a
  TOML parser. Adapted from lakon's and LWPT's scripts/stamp-version.pas. }

{$mode delphi}{$H+}

uses
  Classes,
  SysUtils;

const
  MANIFEST_PATH = 'lwpt.toml';
  OUTPUT_PATH = 'source/units/Version.inc';
  OVERRIDE_VARIABLE = 'WASMLIGHT_VERSION_OVERRIDE';

function ExtractVersion(const ALines: TStringList): string;
var
  i, EqPos: Integer;
  Trimmed, Value: string;
  InPackage: Boolean;
begin
  Result := '';
  InPackage := False;
  for i := 0 to ALines.Count - 1 do
  begin
    Trimmed := Trim(ALines[i]);
    if Trimmed = '' then Continue;
    if Trimmed[1] = '#' then Continue;

    if Trimmed[1] = '[' then
    begin
      InPackage := SameText(Trimmed, '[package]');
      Continue;
    end;

    if not InPackage then Continue;
    if not SameText(Copy(Trimmed, 1, 7), 'version') then Continue;

    EqPos := Pos('=', Trimmed);
    if EqPos = 0 then Continue;

    Value := Trim(Copy(Trimmed, EqPos + 1, MaxInt));
    Value := StringReplace(Value, '"', '', [rfReplaceAll]);
    Value := StringReplace(Value, '''', '', [rfReplaceAll]);
    Result := Trim(Value);
    Exit;
  end;
end;

var
  Lines: TStringList;
  Version, Override_, SourceNote: string;
  Output: TStringList;
begin
  try
    Override_ := Trim(GetEnvironmentVariable(OVERRIDE_VARIABLE));
    if Override_ <> '' then
    begin
      Version := Override_;
      SourceNote := '$' + OVERRIDE_VARIABLE + ' (release tag)';
    end
    else
    begin
      if not FileExists(MANIFEST_PATH) then
      begin
        WriteLn(ErrOutput, 'stamp-version: ', MANIFEST_PATH,
          ' not found (run from repo root)');
        Halt(1);
      end;

      Lines := TStringList.Create;
      try
        Lines.LoadFromFile(MANIFEST_PATH);
        Version := ExtractVersion(Lines);
      finally
        Lines.Free;
      end;

      if Version = '' then
      begin
        WriteLn(ErrOutput,
          'stamp-version: no `version` field in [package] of ',
          MANIFEST_PATH);
        Halt(1);
      end;
      SourceNote := '[package].version in ' + MANIFEST_PATH;
    end;

    Output := TStringList.Create;
    try
      Output.Add('{ Auto-generated by scripts/stamp-version.pas. Do not hand-edit. }');
      Output.Add('{ Source: ' + SourceNote + '. }');
      Output.Add('');
      Output.Add('  PROGRAM_VERSION = ' + QuotedStr(Version) + ';');
      Output.SaveToFile(OUTPUT_PATH);
    finally
      Output.Free;
    end;

    WriteLn('stamp-version: wrote ', OUTPUT_PATH, ' = ', Version,
      ' (from ', SourceNote, ')');
  except
    on E: Exception do
    begin
      WriteLn(ErrOutput, 'stamp-version: ', E.Message);
      Halt(1);
    end;
  end;
end.
